### PR TITLE
Remove `networkId` and `dataMode` from Framework Initialization

### LINKED ISSUE #838: [SDK-Core] Framework initialization Cleanup
## Problems
- **always requires a provider (SUBGRAPH_ONLY mode too)**: As an SDK core user, I would like to use SUBGRAPH_ONLY mode without having to pass in a provider, otherwise SUBGRAPH_ONLY mode seems rather redundant. Given the way that framework creation currently works, it may also make more sense to simply remove SUBGRAPH_ONLY mode option and to ask users to use the query class directly instead of through framework initialization. 
- Remove `networkName` field from SDK-core initialization, Devx has relayed feedback from developers that this is redundant and confusing since the `chainId` property already exists

## Todos

- [x] Remove `dataMode` option from framework #910
- [x] Remove `networkName` property from framework initialization  #910

### PR DESCRIPTION
**Pull request by 0xdavinchee**
* lots of code/tests removed for handling these two options

### CODE REVIEW

**Comment by 0xdavinchee** [comment]
**NOTE: Once this is merged to dev it will be added: #870 and the breaking changes will be released in version 0.4.3**

**Comment by hellwolf** [comment]
How many breakage do you expect there can be by requiring chainId? @0xdavinchee

**Comment by 0xdavinchee** [comment]
> How many breakage do you expect there can be by requiring chainId? @0xdavinchee

it's hard to say - it depends on how many people are using chainId vs. networkName for initialization, but the fix is very simple.

**Review by hellwolf — APPROVED** [review]
let's go

**Pull request merged**
