### PR TITLE
sdk-redux improvements and refactoring

### PR DESCRIPTION
**Pull request by kasparkallas**
Pretty extensive refactor, based on our product needs and experience with the SDK.

The main change is the clear separation of Subgraph and RPC redux slices. The idea is to make a slice per data source so there wouldn't be race-conditions when handling cache invalidation. It's also easier to turn off or enable a certain data source in the application, i.e. in the future I imagine having more data sources (i.e. Superfluid protocol integrations) than Subgraph & RPC. Note that different versions of Subgraph also classify as a separate data source.

The other major change or improvement is the continued development of the transaction (now renamed to "transaction tracker") redux slice. Now there's more data stored on the tracked transactions; SDK user can add metadata; old pending transactions can be re-initiated for tracking when using `redux-persist` and the application got closed before the tracking finished.

### CODE REVIEW

**Comment by hellwolf** [comment]
@kasparkallas what is the state of this one?

**Comment by kasparkallas** [comment]
> @kasparkallas what is the state of this one?

Very much in use in new developments and the PR will be cleaned up for thorough review early this week. Next week we're also having a new internal workshop about it with Sam & anyone else that's interested.

**Comment by saflamini** [comment]
@kasparkallas looks good. Excited to workshop it!

**Comment by kasparkallas** [comment]
Would love to have this merged and get a dev build before the workshop. We already did a internal code review with @0xdavinchee & @hellwolf. The issue is that the code is a bit hard to review because not a lot of product/redux knowledge on the protocol side. I'm not too worried about the rest of the community right now because I'm pretty sure no one else is extensively using it at this point. (Which is super fine and by design -- we're still using it for our own needs first before getting the community more involved.) Once merged, we can also do the update on the Console. The Dashboard V2 is already running on this PR package.

**Review by 0xdavinchee — APPROVED** [review]

**Review by hellwolf — APPROVED** [review]
https://xkcd.com/712/

hmm, deja vu, weird

image

**Pull request merged**
