### PR TITLE
Fix sdk initializations

### PR DESCRIPTION
**Pull request by saflamini**
@JoshuaTrujillo15 @ngmachado 

Outside of the 2 yarn.lock files which were changed, this one is pretty straightforward:

1) Updating some of the examples to use the new SDK Core 
2) Removed networkName and dataMode from scripts and test suites

Let me know if anything looks off to you

@kasparkallas there is an issue though actually with one of the SDK Redux examples. Looks like maybe a peer dependency error? Can you take a look?

### CODE REVIEW

**Review by jtriley2p — CHANGES_REQUESTED** [review]
# Review

`examples/tradeable-cashflow/artifacts`

Please add this directory to the `.gitignore`.

**Review by jtriley2p — DISMISSED** [review]
# Examples

The `@superfluid-finance/ethereum-contracts` versions are mismatched.

Please align versions and do not use commit hashes for versioning.

IE:

```json
"@superfluid-finance/ethereum-contracts": "1.2.3-dev.f94fdbb.0"
```

**Comment by saflamini** [comment]
@JoshuaTrujillo15 - changes have been made:

1-artifacts folder was moved to gitignore for tradeable cashflow
2-ethereum contracts versions have been bumped to 1.3

**Comment by hellwolf** [comment]
@JoshuaTrujillo15 could you have a look a gain?

**Comment by jtriley2p** [comment]
LGTM

**Comment by hellwolf** [comment]
Yes, let's approve and merge!

**Review by hellwolf — APPROVED** [review]

**Pull request merged**
