### PR TITLE
[NETWORK] added optimism-sepolia, scroll-sepolia, scroll-mainnet

### PR DESCRIPTION
**Pull request by d10r**
contracts deployed.

TBD:
[X] bump metadata version
[X] add to subgraph package (implied by adding to metadata?)

### CODE REVIEW

**Comment by hellwolf** [comment]
why nix.flake was updated?

**Comment by d10r** [comment]
> why nix.flake was updated?

good question, hadn't noticed.
Likely because the branch was initially based on gda-deployment-fixes and when rebasing this wasn't reverted? Don't exactly understand why this would happen, but seems the most likely connection. Will undo.

**Review by hellwolf — APPROVED** [review]
great!

btw, did you hand compile the address?

**Comment by d10r** [comment]
> btw, did you hand compile the address?

for the forwarders yes

**Pull request merged**
