### PR TITLE
Subgraph v1 underlying token

### PR DESCRIPTION
**Pull request by 0xdavinchee**
- tests added for decimals and underlyingToken

### CODE REVIEW

**Review by hellwolf — CHANGES_REQUESTED** [review]
@0xdavinchee Please deploy this to feature endpoints, after it's done, test https://user-master.dev.superfluid.dev/dashboard?subgraph_queries_version=feature

**Comment by hellwolf** [comment]
@msoni89 could you test it instead

**Comment by 0xdavinchee** [comment]
@msoni89 @hellwolf this is deployed to both goerli and matic feature endpoints

**Comment by msoni89** [comment]
@0xdavinchee @hellwolf Tested on matic and it seems correct.

image
image
image

**Review by hellwolf — APPROVED** [review]
gmi

**Pull request merged**
