### PR TITLE
Pre release subgraph v1

### PR DESCRIPTION
**Pull request by 0xdavinchee**
Steps to merge
* create pre-release branch
* merge dev into pre-release branch
* submit PR to merge pre-release into release branch

Reason of not using previous method:
- trying to merge dev into release-subgraph-v1 still had issues and it wasn't "in sync" with dev.

### CODE REVIEW

**Comment by hellwolf** [comment]
@0xdavinchee should add some release branch checks

**Comment by hellwolf** [comment]
image

what could it be

**Comment by 0xdavinchee** [comment]
> image
> 
> what could it be

not sure if I have permissions to do it, but I think for `release-subgraph-v1` branch: `ci.pre-release-subgraph.yml` and for `release-sdk-core-stable`: `ci.pre-release-sdk-core.yml`.

**Comment by 0xdavinchee** [comment]
it's strange that the ci.pre-release-subgraph workflow didn't run though even though it satisfies the trigger... am I missing something obvious here?

```
on:
    pull_request:
      branches:
        - "release-subgraph-v1"
      paths:
        - "packages/sdk-core/**"
        - "packages/subgraph/**"
        - ".github/workflows/ci.pre-release-subgraph.yml"
        - ".github/workflows/call.setup-deploy-and-test-local-subgraph.yml"
        - ".github/workflows/call.test-subgraph-on-previous-sdk-core-versions.yml"
```

**Pull request merged**
