### PR TITLE
[ETHEREUM-CONTRACTS] Further Refactoring Cleanup

### PR DESCRIPTION
**Pull request by 0xdavinchee**
* use BigNumber almost everywhere
* use expect more
* remove js-sdk usage as much as possible
* remove web3 usage as much as possible

### CODE REVIEW

**Comment by hellwolf** [comment]
> remove js-sdk usage as much as possible

But we removed it from repo, how it is still refereneced?

**Comment by hellwolf** [comment]
"@superfluid-finance/js-sdk": "0.6.3",

oh no, it is still in the package.json.

**Comment by hellwolf** [comment]
```
$ grep @superfluid-finance/js-sdk packages/ethereum-contracts/ -R
packages/ethereum-contracts/package.json:        "@superfluid-finance/js-sdk": "0.6.3",
packages/ethereum-contracts/scripts/deploy-unlisted-pure-super-token.js:const SuperfluidSDK = require("@superfluid-finance/js-sdk");
packages/ethereum-contracts/scripts/deploy-aux-contracts.js:const SuperfluidSDK = require("@superfluid-finance/js-sdk");packages/ethereum-contracts/scripts/deploy-framework.js:const SuperfluidSDK = require("@superfluid-finance/js-sdk");
packages/ethereum-contracts/scripts/gov-transfer-framework-ownership.js:const SuperfluidSDK = require("@superfluid-finance/js-sdk");
packages/ethereum-contracts/scripts/gov-upgrade-super-token-logic.js:const SuperfluidSDK = require("@superfluid-finance/js-sdk");
packages/ethereum-contracts/scripts/libs/getConfig.js:const SuperfluidSDK = require("@superfluid-finance/js-sdk");
packages/ethereum-contracts/scripts/info-inspect-account.js:const SuperfluidSDK = require("@superfluid-finance/js-sdk");packages/ethereum-contracts/scripts/resolver-list-super-token.js:const SuperfluidSDK = require("@superfluid-finance/js-sdk");
packages/ethereum-contracts/scripts/info-show-protocol.js:const SuperfluidSDK = require("@superfluid-finance/js-sdk");
packages/ethereum-contracts/scripts/info-print-contract-addresses.js:const SuperfluidSDK = require("@superfluid-finance/js-sdk");
packages/ethereum-contracts/scripts/deploy-deterministically.js:const SuperfluidSDK = require("@superfluid-finance/js-sdk");
packages/ethereum-contracts/scripts/gov-set-3Ps-config.js:const SuperfluidSDK = require("@superfluid-finance/js-sdk");
packages/ethereum-contracts/scripts/gov-set-trusted-forwarder.js:const SuperfluidSDK = require("@superfluid-finance/js-sdk");
packages/ethereum-contracts/scripts/info-list-apps.js:const SuperfluidSDK = require("@superfluid-finance/js-sdk");
packages/ethereum-contracts/scripts/gov-create-new-app-registration-key.js:const SuperfluidSDK = require("@superfluid-finance/js-sdk");
packages/ethereum-contracts/scripts/resolver-register-token.js:const SuperfluidSDK = require("@superfluid-finance/js-sd
");
packages/ethereum-contracts/scripts/deploy-unlisted-super-token.js:const SuperfluidSDK = require("@superfluid-finance/js-sdk");
packages/ethereum-contracts/scripts/gov-create-new-factory-registration.js:const SuperfluidSDK = require("@superfluid-finance/js-sdk");
packages/ethereum-contracts/scripts/gov-set-reward-address.js:const SuperfluidSDK = require("@superfluid-finance/js-sdk");
packages/ethereum-contracts/scripts/deploy-super-token.js:const SuperfluidSDK = require("@superfluid-finance/js-sdk");
packages/ethereum-contracts/scripts/gov-set-token-min-deposit.js:const SuperfluidSDK = require("@superfluid-finance/js-sdk");
packages/ethereum-contracts/scripts/resolver-unlist-super-token.js:const SuperfluidSDK = require("@superfluid-finance/js-sdk");
packages/ethereum-contracts/scripts/deploy-test-token.js:const SuperfluidSDK = require("@superfluid-finance/js-sdk");
packages/ethereum-contracts/test/TestEnvironment.ts:const SuperfluidSDK = require("@superfluid-finance/js-sdk");
```

Okay..

**Comment by hellwolf** [comment]
It's fine then.

**Comment by 0xdavinchee** [comment]
although I would like to remove the js-sdk dependencies from ethereum-contracts entirely, this would require a giant refactor of all the scripts (as you've seen above) and a rabbit hole that's not worth going down right now.

**Comment by hellwolf** [comment]
yea, it's fine, I'm surprised that testFramework still relies on it

**Review by hellwolf — APPROVED** [review]
let's go

**Comment by 0xdavinchee** [comment]
> yea, it's fine, I'm surprised that testFramework still relies on it

Oh yeah, the first thing I tried was to remove this from `TestEnvironment.ts`, but this was also a rabbit hole that I chose not to go down. 

JS-SDK Framework's `.initialize()` function is doing a bunch of stuff behind the scenes which if not called breaks the test suite. 😕

**Comment by hellwolf** [comment]
> > yea, it's fine, I'm surprised that testFramework still relies on it
> 
> Oh yeah, the first thing I tried was to remove this from `TestEnvironment.ts`, but this was also a rabbit hole that I chose not to go down.
> 
> JS-SDK Framework's `.initialize()` function is doing a bunch of stuff behind the scenes which if not called breaks the test suite. 😕

SDK-CORE should have feature parity of these.

Or rather ethereum-contracts not have dependencies to any SDK.

**Comment by 0xdavinchee** [comment]
> > > yea, it's fine, I'm surprised that testFramework still relies on it
> > 
> > 
> > Oh yeah, the first thing I tried was to remove this from `TestEnvironment.ts`, but this was also a rabbit hole that I chose not to go down.
> > JS-SDK Framework's `.initialize()` function is doing a bunch of stuff behind the scenes which if not called breaks the test suite. 😕
> 
> SDK-CORE should have feature parity of these.
> 
> Or rather ethereum-contracts not have dependencies to any SDK.

I agree, not having any dependencies to any SDKs is probably the most ideal solution.

**Comment by hellwolf** [comment]
image

**Pull request merged**
