### PR TITLE
Fix canary build

### PR DESCRIPTION
**Pull request by hellwolf**

### CODE REVIEW

**Comment by samirsalem** [comment]
I've forked the repo and try to reproduce/fix in fork before submitting a PR

**Comment by hellwolf** [comment]
thank you!

**Comment by hellwolf** [comment]
https://github.com/npm/cli/issues/3993

> As you can see, using npa returns returns GIT SSH result when subpaths are passed to it. If you add a trailing "/" at the end of your path, it should fix the issue:

😡

**Review by 0xdavinchee — APPROVED** [review]
lgtm

**Pull request merged**
