### PR TITLE
Subgraph data integrity validation

### LINKED ISSUE #421: [SUBGRAPH] Data integrity validation scripts
As a protocol subgraph v1 endpoint consumer, the integrity of the data is vital. Data from web3 nodes is still considered the closest source of truth and can be used for data integrity validation. So a periodical data integrity check validate protocol subgraph v1 against web3 data can boost the confidence of protocol subgraph downstream consumers.

## Spec
Account Invariance Validations
- [ ] a.0 Balance data matching: RTB + Claimable === subgraph calculated balance
- [x] a.1 CFA data matching: netflow  (and its last updated timestamp)
- [x] a.2 IDA data matching: subscriber subscription data, and publisher index data

Global Invariance Validations
- [x] g.0 total supply should match super token AUM 
- [x] g.1 CFA total netflow should be zero
- [x] g.2 IDA total units sum of subscribers should match their respective publisher index units
- [x] g.3 #573
- [x] g.4 Subgraph CFA/IDA events length === on chain FlowUpdatedEvents length AND properties are matching
## Notes

image

### PR DESCRIPTION
**Pull request by 0xdavinchee**
* subgraph data integrity scripts test the invariants specified here: https://github.com/superfluid-finance/protocol-monorepo/wiki/Subgraph-Data-Integrity-Invariants-Reference
* `hardhat.config.ts` and `README.md` updated to add support for additional networks
* overall refactoring of the integrity tests file for more maintainability + more descriptive logs
* related to https://github.com/superfluid-finance/protocol-monorepo/issues/421

### CODE REVIEW

**Comment by hellwolf** [comment]
@d10r & @ngmachado who wants to step forward and help @0xdavinchee to merge this pull request finally? Let's sync.

**Comment by ngmachado** [comment]
This could be very heavy to run in git-actions. We should analyse the possibility of running this along with solvency-checker

**Review by ngmachado — APPROVED** [review]
LGTM

**Review by hellwolf — CHANGES_REQUESTED** [review]
integrate it to our solvency routines as a regular report

**Review by hellwolf — APPROVED** [review]

**Pull request merged**
