### PR TITLE
Renamed MaticBridgedNativeSuperToken to MaticBridgedPureSuperToken

### PR DESCRIPTION
**Pull request by d10r**
renaming needed due to our new classification/terminology, see https://github.com/superfluid-finance/protocol-monorepo/wiki/About-Super-Token-Classification

### CODE REVIEW

**Review by hellwolf — CHANGES_REQUESTED** [review]
this should be migrated to : https://github.com/superfluid-finance/custom-supertokens

**Comment by ngmachado** [comment]
This PR was converted and merge to another repo: https://github.com/superfluid-finance/custom-supertokens/pull/10

After the files be removed from this repo, we can close this PR.

**Comment by hellwolf** [comment]
Yes, let's delete files!

**Comment by ngmachado** [comment]
We can close this PR.

**Pull request closed without merging**
