### PR TITLE
[ETHEREUM-CONTRACTS] README on forge install

### PR DESCRIPTION
**Pull request by shafu0x**

### CODE REVIEW

**Comment by hellwolf** [comment]
image

**Comment by hellwolf** [comment]
```
$ forge install --no-commit superfluid-finance/protocol-monorepo@26e8da8

$ tree -d lib/protocol-monorepo/
lib/protocol-monorepo/
├── lib
│   └── forge-std
│       ├── lib
│       │   └── ds-test
│       │       ├── demo
│       │       └── src
│       ├── src
│       │   └── interfaces
│       └── test
│           ├── compilation
│           └── fixtures
├── packages
│   ├── automation-contracts
│   │   ├── autowrap
│   │   │   ├── contracts
│   │   │   │   ├── interfaces
│   │   │   │   ├── mocks
│   │   │   │   └── strategies
│   │   │   ├── deploy
│   │   │   ├── script
│   │   │   └── test
│   │   └── scheduler
│   │       ├── audit
│   │       ├── contracts
│   │       │   └── interface
│   │       ├── deploy
│   │       └── test
│   ├── ethereum-contracts
│   │   ├── audits
│   │   ├── contracts
│   │   │   ├── agreements
│   │   │   ├── apps
│   │   │   ├── gov
│   │   │   ├── interfaces
│   │   │   │   ├── agreements
│   │   │   │   ├── superfluid
│   │   │   │   ├── tokens
│   │   │   │   └── utils
│   │   │   ├── libs
│   │   │   ├── mocks
│   │   │   ├── superfluid
│   │   │   ├── tokens
│   │   │   ├── upgradability
│   │   │   └── utils
│   │   ├── dev-scripts
│   │   ├── docs
│   │   │   └── docgen-templates
│   │   ├── ops-scripts
│   │   │   ├── artifacts
│   │   │   └── libs
│   │   ├── scripts
│   │   ├── tasks
│   │   ├── test
│   │   │   ├── contracts
│   │   │   │   ├── agreements
│   │   │   │   ├── apps
│   │   │   │   ├── gov
│   │   │   │   ├── libs
│   │   │   │   ├── scenarios
│   │   │   │   ├── superfluid
│   │   │   │   ├── tokens
│   │   │   │   ├── upgradability
│   │   │   │   └── utils
│   │   │   ├── foundry
│   │   │   │   ├── agreements
│   │   │   │   ├── apps
│   │   │   │   ├── deployments
│   │   │   │   ├── libs
│   │   │   │   ├── performance
│   │   │   │   ├── superfluid
│   │   │   │   │   └── nftUpgradability
│   │   │   │   └── utils
│   │   │   ├── ops-scripts
│   │   │   └── utils
│   │   ├── testsuites
│   │   └── utils
│   ├── hot-fuzz
│   │   ├── contracts
│   │   │   └── superfluid-tests
│   │   └── tasks
│   ├── js-sdk
│   │   ├── src
│   │   │   ├── types
│   │   │   └── utils
│   │   │       └── gasMetering
│   │   ├── tasks
│   │   └── test
│   │       └── utils
│   ├── sdk-core
│   │   ├── contracts
│   │   ├── previous-versions-testing
│   │   ├── scripts
│   │   ├── src
│   │   │   └── subgraph
│   │   │       ├── entities
│   │   │       │   ├── account
│   │   │       │   ├── accountTokenSnapshot
│   │   │       │   ├── accountTokenSnapshotLog
│   │   │       │   ├── index
│   │   │       │   ├── indexSubscription
│   │   │       │   ├── stream
│   │   │       │   ├── streamPeriod
│   │   │       │   ├── token
│   │   │       │   ├── tokenStatistic
│   │   │       │   └── tokenStatisticLog
│   │   │       ├── events
│   │   │       ├── meta
│   │   │       └── queries
│   │   ├── tasks
│   │   └── test
│   ├── sdk-redux
│   │   ├── src
│   │   │   ├── reduxSlices
│   │   │   │   ├── rtkQuery
│   │   │   │   │   ├── cacheTags
│   │   │   │   │   ├── rpcApiSlice
│   │   │   │   │   │   └── endpoints
│   │   │   │   │   └── subgraphApiSlice
│   │   │   │   │       └── endpoints
│   │   │   │   └── transactionTrackerSlice
│   │   │   │       └── thunks
│   │   │   └── typings
│   │   └── tasks
│   ├── sdk-redux-examples
│   │   ├── sdk-redux-nextjs-typescript
│   │   │   ├── components
│   │   │   ├── pages
│   │   │   │   └── tokens
│   │   │   │       ├── ssg
│   │   │   │       └── ssr
│   │   │   ├── public
│   │   │   ├── redux
│   │   │   └── styles
│   │   └── sdk-redux-react-typecript
│   │       ├── public
│   │       └── src
│   │           ├── features
│   │           │   └── generic-entity-queries
│   │           └── redux
│   ├── solidity-semantic-money
│   ├── spec-haskell
│   │   ├── maths
│   │   ├── pkgs
│   │   │   ├── core
│   │   │   │   ├── src
│   │   │   │   │   ├── Data
│   │   │   │   │   │   └── Type
│   │   │   │   │   └── Money
│   │   │   │   │       ├── Systems
│   │   │   │   │       │   └── Superfluid
│   │   │   │   │       │       ├── Agreements
│   │   │   │   │       │       │   ├── ProportionalDistribution
│   │   │   │   │       │       │   └── Universal
│   │   │   │   │       │       ├── Concepts
│   │   │   │   │       │       ├── CoreTypes
│   │   │   │   │       │       ├── MonetaryUnitData
│   │   │   │   │       │       └── SubSystems
│   │   │   │   │       └── Theory
│   │   │   │   ├── src-internal -> ../src-internal
│   │   │   │   └── test
│   │   │   │       └── Money
│   │   │   │           └── Systems
│   │   │   │               └── Superfluid
│   │   │   ├── simple
│   │   │   │   ├── src
│   │   │   │   │   ├── Data
│   │   │   │   │   │   └── Type
│   │   │   │   │   └── Money
│   │   │   │   │       └── Systems
│   │   │   │   │           └── Superfluid
│   │   │   │   │               └── Instances
│   │   │   │   │                   └── Simple
│   │   │   │   ├── src-internal -> ../src-internal
│   │   │   │   └── test
│   │   │   │       └── Money
│   │   │   │           └── Systems
│   │   │   │               └── Superfluid
│   │   │   ├── src-internal
│   │   │   │   └── Lens
│   │   │   └── validator
│   │   │       └── src
│   │   │           └── Money
│   │   │               └── Systems
│   │   │                   └── Superfluid
│   │   │                       └── Validator
│   │   ├── utils
│   │   └── yellowpaper
│   │       └── assets
│   └── subgraph
│       ├── cache
│       ├── config
│       ├── scripts
│       │   └── dataIntegrity
│       ├── src
│       │   └── mappings
│       ├── tasks
│       ├── test
│       │   ├── helpers
│       │   ├── queries
│       │   └── validation
│       │       └── hol
│       ├── tests
│       │   ├── cfav1
│       │   │   ├── event
│       │   │   └── hol
│       │   ├── host
│       │   ├── idav1
│       │   │   └── event
│       │   ├── resolver
│       │   ├── superfluidGovernance
│       │   ├── superToken
│       │   │   └── event
│       │   ├── superTokenFactory
│       │   └── toga
│       │       └── event
│       └── types
└── tasks

217 directories
```

Note the '@tag' thing, otherwise you end up installing a very old version of the repo. I would recommend pick a tag e.g 'ethereum-contracts@v1.5.2' (https://github.com/superfluid-finance/protocol-monorepo/tree/ethereum-contracts%40v1.5.2) and use its git commit hash to install.

Unfortunately, not so monorepo friendly tooling.

**Comment by shafu0x** [comment]
@hellwolf yeah good point. had the same issue. would probably need to be implemented in the CI/CD pipeline.

This is what I used: `forge install superfluid-finance/ethereum-contracts@1.5.2_deployment`
or:`forge install superfluid-finance/ethereum-contracts@ethereum-contracts@1.5.2`

The version number would have to be a placeholder in the docs.

**Comment by hellwolf** [comment]
```
$ forge install superfluid-finance/ethereum-contracts@ethereum-contracts@1.5.2
Installing ethereum-contracts in "/home/hellwolf/tmp/t/lib/ethereum-contracts" (url: Some("ethereum-contracts"), tag: Some("1.5.2"))
Error: 
The target directory is a part of or on its own an already initialized git repository,
and it requires clean working and staging areas, including no untracked files.

Check the current git repository's status with `git status`.
Then, you can track files with `git add ...` and then commit them with `git commit`,
ignore them in the `.gitignore` file, or run this command again with the `--no-commit` flag.

If none of the previous steps worked, please open an issue at:
https://github.com/foundry-rs/foundry/issues/new/choose
```

~~This wouldn't work because unfortunately our tag containing a '@' that breaks the forge cli.~~

Wrong output.

**Review by hellwolf — CHANGES_REQUESTED** [review]
Provided instruction needs improvements.

**Comment by shafu0x** [comment]
@hellwolf no it works. You have another issue. You need to commit your changes before you can install a new package.

**Comment by hellwolf** [comment]
```
$ forge install superfluid-finance/ethereum-contracts@ethereum-contracts@1.5.2
Installing ethereum-contracts in "/home/hellwolf/tmp/t/lib/ethereum-contracts" (url: Some("ethereum-contracts"), tag: Some("1.5.2"))

Error: 
fatal: repo URL: 'ethereum-contracts' must be absolute or begin with ./|../

$ forge --version
forge 0.2.0 (c49e5e1 2023-04-09T00:10:31.029008846Z)
```

Yea, wrong output. I did it again here.

What forge version you use?

**Comment by shafu0x** [comment]
```
$ forge --version
forge 0.2.0 (ed9298d 2023-03-10T00:18:34.475694Z)
```

**Comment by shafu0x** [comment]
but you are right. I get the same error in a blank foundry project. the @ is probably the problem I guess.

**Comment by hellwolf** [comment]
Yea, that must be it.

I can think of workaround, one could go to https://github.com/superfluid-finance/protocol-monorepo/releases/tag/ethereum-contracts%40v1.5.2 and extract the commit hash highlighted:

image


Then you could do 

```
forge install superfluid-finance/ethereum-contracts@26e8da8
```

A bit harder to write a concise/one liner README instruction this way.

**Comment by shafu0x** [comment]
very good point, that works too!

I just posted the question in the foundry telegram. Maybe there is a way to escape the second @.

**Comment by hellwolf** [comment]
Double checking if it is tolerated by  "standard":

https://git-scm.com/docs/git-check-ref-format

>  8. They cannot contain a sequence @{.
>  9. They cannot be the single character @.

You may argue, the tags used in this repo is compliant by these criteria.

**Review by hellwolf — APPROVED** [review]
I updated the foundry related command

**Comment by hellwolf** [comment]
@shafu0x 

```sh
$ forge install superfluid-protocol-monorepo=superfluid-finance/protocol-monorepo@dev
$ # or using ethereum-contracts@v1.6.0
$ forge install superfluid-protocol-monorepo=superfluid-finance/protocol-monorepo@$(git ls-remote https://github.com/superfluid-finance/protocol-monorepo.git ethereum-contracts@v1.6.0 | awk '{print $1}')
```

This should be good now.

**Pull request merged**
