### PR TITLE
Refactor SuperfluidFrameworkDeployer & ERC1820RegistryCompiled

### PR DESCRIPTION
**Pull request by hellwolf**
- SuperfluidFrameworkDeployer.getFramework to return structure for future proof
- ERC1820RegistryCompiled to be shipped for code reusability in test framework.

### CODE REVIEW

**Comment by hellwolf** [comment]
TODO ship libs as part of the Framework struct.

**Comment by hellwolf** [comment]
@0xdavinchee ready to have a look

**Review by 0xdavinchee — APPROVED** [review]
looks good, LGTM

**Comment by 0xdavinchee** [comment]
@hellwolf I think I will refactor my open PRs to use the framework deployer/foundry tester

**Pull request merged**
