### PR TITLE
[WORKFLOWS] Update  Nixpkgs Inputs & Update Node Dependencies

### PR DESCRIPTION
**Pull request by hellwolf**
- update nixpkgs
- update ghc
- added node20, but keep node18 as default since subgraph local testing doesn't work with it.
- remove certora
- update node depenencies target minor versions.

Postponing to future PRs:

- next steps:
  - graphql-request related major version update:
    ```
     @graphql-codegen/cli                    ^2.16.5  →  ^5.0.0
     @graphql-codegen/introspection           ^2.2.3  →  ^4.0.0
     @graphql-codegen/typed-document-node    ^2.3.13  →  ^5.0.1
     @graphql-codegen/typescript              ^2.8.8  →  ^4.0.1
     @graphql-codegen/typescript-operations  ^2.5.13  →  ^4.0.1
     ethers                                    5.7.2  →   6.7.0
     graphql-request                          ^4.3.0  →  ^6.1.0
     ```
  - node20-by-default update.
  - improve ethereum-contracts artifacts packaging (1.8.0 release).
  - improve metadata packaging, to support more framework.
- aspirational next steps, keeping up with the Kardashians
  - pnpm migration.
  - sdk-core v2 with multi-frameworks support
- probably never:
  - ethers-v6 update.

### CODE REVIEW

**Comment by hellwolf** [comment]
[merged](https://github.com/NixOS/nixpkgs/pull/230067#discussion_r1270320924) merged, will address this one soon.

**Comment by hellwolf** [comment]
All packages up to date, targeting minor version updates:

```
nix-shell$ yarn workspaces run check-updates 
yarn workspaces v1.22.19

> @superfluid-finance/solidity-semantic-money
yarn run v1.22.19
$ ncu --target minor
Using yarn
Checking /home/hellwolf/Projects/superfluid/protocol-monorepo.worktree/update_nix_flake_inputs/packages/solidity-semantic-money/package.json
[====================] 1/1 100%

All dependencies match the minor package versions :)
Done in 1.09s.

> @superfluid-finance/ethereum-contracts
yarn run v1.22.19
$ ncu --target minor --dep prod,dev
Using yarn
Checking /home/hellwolf/Projects/superfluid/protocol-monorepo.worktree/update_nix_flake_inputs/packages/ethereum-contracts/package.json
[====================] 22/22 100%

All dependencies match the minor package versions :)
Done in 3.56s.

> @superfluid-finance/metadata
yarn run v1.22.19
$ ncu --target minor
Using yarn
Checking /home/hellwolf/Projects/superfluid/protocol-monorepo.worktree/update_nix_flake_inputs/packages/metadata/package.json

No dependencies.
Done in 0.83s.

> @superfluid-finance/js-sdk
yarn run v1.22.19
$ ncu --target minor --dep prod,dev
Using yarn
Checking /home/hellwolf/Projects/superfluid/protocol-monorepo.worktree/update_nix_flake_inputs/packages/js-sdk/package.json
[====================] 9/9 100%

All dependencies match the minor package versions :)
Done in 2.63s.

> @superfluid-finance/sdk-core
yarn run v1.22.19
$ ncu --target minor --dep prod,dev
Using yarn
Checking /home/hellwolf/Projects/superfluid/protocol-monorepo.worktree/update_nix_flake_inputs/packages/sdk-core/package.json
[====================] 17/17 100%

All dependencies match the minor package versions :)
Done in 6.69s.

> @superfluid-finance/sdk-redux
yarn run v1.22.19
$ ncu --target minor --dep prod,dev
Using yarn
Checking /home/hellwolf/Projects/superfluid/protocol-monorepo.worktree/update_nix_flake_inputs/packages/sdk-redux/package.json
[====================] 10/10 100%

All dependencies match the minor package versions :)
Done in 2.40s.

> @superfluid-finance/subgraph
yarn run v1.22.19
$ ncu --target minor --dep prod,dev
Using yarn
Checking /home/hellwolf/Projects/superfluid/protocol-monorepo.worktree/update_nix_flake_inputs/packages/subgraph/package.json
[====================] 10/10 100%

All dependencies match the minor package versions :)
Done in 2.68s.

> @superfluid-finance/hot-fuzz
yarn run v1.22.19
$ ncu --target minor
Using yarn
Checking /home/hellwolf/Projects/superfluid/protocol-monorepo.worktree/update_nix_flake_inputs/packages/hot-fuzz/package.json
[====================] 2/2 100%

All dependencies match the minor package versions :)
Done in 1.11s.

> scheduler
yarn run v1.22.19
$ ncu --target minor
Using yarn
Checking /home/hellwolf/Projects/superfluid/protocol-monorepo.worktree/update_nix_flake_inputs/packages/automation-contracts/scheduler/package.json
[====================] 3/3 100%

All dependencies match the minor package versions :)
Done in 1.09s.

> autowrap
yarn run v1.22.19
$ ncu --target minor
Using yarn
Checking /home/hellwolf/Projects/superfluid/protocol-monorepo.worktree/update_nix_flake_inputs/packages/automation-contracts/autowrap/package.json
[====================] 3/3 100%

All dependencies match the minor package versions :)
Done in 1.06s.
Done in 25.17s.
```

**Comment by hellwolf** [comment]
https://github.com/superfluid-finance/protocol-monorepo/actions/runs/5831436532/job/15814866280?pr=1390

Create PR Artifact broken by [lerna update](https://github.com/nrwl/nx/issues/18247). Let it be fore now, to be fixed.

**Review by 0xdavinchee — APPROVED** [review]
LGTM

**Pull request merged**
