### PR TITLE
Fixing hot-fuzz

### PR DESCRIPTION
**Pull request by hellwolf**

### CODE REVIEW

**Comment by hellwolf** [comment]
image

**Comment by hellwolf** [comment]
image

[covered.1675854277.txt](https://github.com/superfluid-finance/protocol-monorepo/files/10684845/covered.1675854277.txt)

**Comment by hellwolf** [comment]
It's back :)

**Comment by hellwolf** [comment]
```
./hot-fuzz contracts/superfluid-tests/SuperHotFuzz.yaml
```

**Review by 0xdavinchee — APPROVED** [review]

**Pull request merged**
