### PR TITLE
Sdkcore updates new fields and entities changes

### PR DESCRIPTION
**Pull request by msoni89**
Reverts superfluid-finance/protocol-monorepo#836

### CODE REVIEW

**Comment by 0xdavinchee** [comment]
NOTE: only approve + merge once all dev endpoints have been indexed: 
- https://github.com/superfluid-finance/protocol-monorepo/actions/runs/2352446664
- https://portal.dev.superfluid.dev/subgraph.html

**Comment by 0xdavinchee** [comment]
next steps:
1. merge https://github.com/superfluid-finance/protocol-monorepo/pull/835
2. merge this branch so sdk-core is synced up with deployed subgraph at dev endpoints
3. submit a PR to merge dev into release-subgraph-v1
4. deploy to v1 endpoints
5. wait for v1 endpoints to complete indexing on all networks
6. release new sdk-core version on npm

**Review by 0xdavinchee — APPROVED** [review]
LGTM...
next steps:
- merge this branch so sdk-core is synced up with deployed subgraph at dev endpoints
- submit a PR to merge dev into release-subgraph-v1
- deploy to v1 endpoints
- wait for v1 endpoints to complete indexing on all networks
- release new sdk-core version on npm

**Comment by hellwolf** [comment]
Please remove "[RFR] " from commit messages...

**Review by hellwolf — APPROVED** [review]
let's go

**Pull request merged**
