### PR TITLE
GH workflow for deploying to mainnets

### PR DESCRIPTION
**Pull request by d10r**
mostly a copy of deploy-to-testnets

### CODE REVIEW

**Comment by d10r** [comment]
Can't figure out how to trigger this workflow from the UI. When I added a workflow for docs generation, it appeared automatically.
What a I missing?

**Comment by d10r** [comment]
workflow still not showing up in Actions tab. @hellwolf do you know why that is?

**Comment by hellwolf** [comment]
github limitation, until it's merged to dev, it is not available for the first time

**Review by hellwolf — APPROVED** [review]

**Comment by d10r** [comment]
results of first attempt weren't great:
* xdai: failed to run verify script bcs no etherscan support, being addressed in https://github.com/superfluid-finance/protocol-monorepo/tree/workflow-improvements
* optimism: [timed out](https://github.com/superfluid-finance/protocol-monorepo/runs/6992715316?check_suite_focus=true)
* arbitrum: [timed out](https://github.com/superfluid-finance/protocol-monorepo/runs/6992832120?check_suite_focus=true)
* avalanche: [immediate failure](https://github.com/superfluid-finance/protocol-monorepo/runs/6992449345?check_suite_focus=true#step:6:27) - likely missing env for RPC

All networks: verification can't succeed bcs at the time of invocation the proxies don't yet point to the new logic contracts.
Possible solutions:
1.  decouple verification (manually trigger after executing the multisig txs)
2.  verification script which verifies the implementation contracts (not indirectly through the proxies)

Option 1 is quicker tbd for the short term.  
Option 2 is better long term, bcs eventually we'll want multisig signers to easily verify what they're upgrading to.

My recommendations for next actions:
* keep mainnet upgrades single-network actions. Maybe provide a workflow which requires only the network name as input
* provide a workflow for verifying all mainnets
* add Avalanche RPC env
* investigate what's happening on L2s. Since upgrades are atomic (unlike 1st time deployment, already-deployed contracts aren't picked up and re-used by consecutive runs), having to re-run burns considerable amounts of gas. Even just seeing which RPC was used would already be helpful.

**Pull request merged**
