### PR TITLE
[js-sdk] Add back needed gas dependencies

### PR DESCRIPTION
**Pull request by pi0neerpat**
js-sdk v0.2.3 is breaking due to missing dependencies required by the new gas metering feature.

### CODE REVIEW

**Comment by pi0neerpat** [comment]
Lets merge asap

**Comment by hellwolf** [comment]
```
$ grep -Eho 'require\("[^.].*"\)' src/ -R |sort |uniq
require("fs")
require("@openzeppelin/test-helpers")
require("@openzeppelin/test-helpers/src/setup")
require("path")
require("@superfluid-finance/js-sdk")
require("@truffle/contract")
require("web3")
```

**Review by hellwolf — APPROVED** [review]

**Comment by hellwolf** [comment]
@pi0neerpat have a look, we can then publish

**Comment by hellwolf** [comment]
now

```
$ grep -Eho 'require\("[^.].*"\)' src/ -R |sort |uniq
require("fs")
require("path")
require("@superfluid-finance/js-sdk")
require("@truffle/contract")
require("web3")
```

**Pull request merged**
