### PR TITLE
[ETHEREUM-CONTRACTS] set evm target to "paris"

### LINKED ISSUE #1533: [SPIKE] EVM bytecode compatibility across SF networks
The solidity compiler has a configurable EVM version target, see
https://docs.soliditylang.org/en/v0.8.21/using-the-compiler.html#input-description

This defaults to what's deployed on Ethereum.
We don't currently have a process in place for ensuring that the bytecode we create is compatible with all EVM networks it's deployed to.

Task:
Investigate if there's any risks here / what they are / how to mitigate

### PR DESCRIPTION
**Pull request by d10r**
Reason: #1533

### CODE REVIEW

**Review by 0xdavinchee — APPROVED** [review]
thanks for doing this 👍🏼

**Comment by hellwolf** [comment]
I want to see a code with PUSH0 generated.

**Comment by hellwolf** [comment]
Okay, so foundry cast disassemble doesn't support PUSH0 yet, but the evidence suggest that it should be generated already.

$ solc-0.8.21 --evm-version paris erc20.sol --bin | tail -n1 | xargs cast disassemble   | wc -c
50197

$ solc-0.8.21 --evm-version paris erc20.sol --bin | tail -n1 | xargs cast disassemble   | grep INVALID
00000457: INVALID
000014cd: INVALID
000014d5: INVALID
000014d8: INVALID
000014f2: INVALID
000014f3: INVALID
000014f7: INVALID


$ solc-0.8.21 --evm-version shanghai erc20.sol --bin | tail -n1 | xargs cast disassemble   | wc -c
49869

$ solc-0.8.21 --evm-version shanghai erc20.sol --bin | tail -n1 | xargs cast disassemble   | grep INVALID | wc -l
182

**Comment by hellwolf** [comment]
I will piggyback a monthly foundry update here.

**Comment by hellwolf** [comment]
search twitter PUSH0, it's fun to read :)

**Review by hellwolf — APPROVED** [review]

**Pull request merged**
