### PR TITLE
ci: optimized pull request packages build process.

### LINKED ISSUE #641: [WORKFLOW] Optimize pull request packages build process
## Background

To make testing of feature branch builds easy, currently all pull requests create its own PR npm packages published to the _github package registry_. More about the process can be found in https://github.com/superfluid-finance/protocol-monorepo/wiki/Branch-Policy

## Problem

Currently the workflow is not done in a very resource conscious fashion. Each commits would trigger a PR package publish, and they are never cleaned up after the pull requests are closed.

## Proposed Solution

- Use workflow_call more
- We would want to trigger the PR builds by commenting in the pull request something like "Bot, please #build-pr-packages".
- Create A github periodical job to cleanup of stale PR packages in github registry.

## Bounty reward

500 DAIx payable on Polygon in Super DAI (DAIx)

### PR DESCRIPTION
**Pull request by zhyd1997**
to resolve: #641

## Checklist

- [ ] Use workflow_call to trigger `handler.publish-pr-packages.yml`
- [x]  We would want to trigger the PR builds by commenting in the pull request something like "Bot, please #build-pr-packages".
- [x] Create A github periodical job to cleanup of stale PR packages in github registry.

### CODE REVIEW

**Comment by hellwolf** [comment]
@zhyd1997 please use pattern matching for comment body that contains the tag "#build-pr-packages"

Also created a checklist of things need to be covered.

**Comment by zhyd1997** [comment]
@hellwolf 
Could you tell me about the checklist?

**Comment by hellwolf** [comment]
It's in the description

**Comment by zhyd1997** [comment]
@hellwolf 

I don't use `workflow_call`, but I think it will work well.

**Comment by hellwolf** [comment]
Hi @zhyd1997 thanks for helping out the bounty so far. It is already valuable, we would though need a bit more work in actually optimizing the whole workflows, I will need to refine the requirements a bit more before continuing further. Meanwhile, Superfluid definitely would be glad to pay a partial bounty out to you for your work so far. Could you identify yourself in our discord #bounties channel, so that we could proceed next?

**Comment by zhyd1997** [comment]
@hellwolf 
Joined the channel, if you have any questions about the pull request, please let me know.

**Comment by hellwolf** [comment]
to be continued...

**Pull request closed without merging**
