### PR TITLE
Add TransferEvents support to sdk-(core/redux)

### PR DESCRIPTION
**Pull request by kasparkallas**
Why?
To make it possible to query transfers.

### CODE REVIEW

**Comment by kasparkallas** [comment]
What the-... too many "files changed":

**Review by Mikkoun — APPROVED** [review]

**Review by 0xdavinchee — APPROVED** [review]
Looks good - LGTM

**Review by 0xdavinchee — DISMISSED** [review]
@kasparkallas, although  it looks like example build is failing.

**Comment by hellwolf** [comment]
seems temporary issue, and example projects in general don't block merging

**Comment by hellwolf** [comment]
try to rebuild them if they persist, if so report to Sam.

**Review by 0xdavinchee — APPROVED** [review]
LGTM pt2

**Pull request merged**
