### PR TITLE
Create Hardhat Deployer

### PR DESCRIPTION
**Pull request by jtriley2p**
Changes have been made to reflect previous feedback [here](https://github.com/superfluid-finance/protocol-monorepo/pull/944).

### CODE REVIEW

**Comment by jtriley2p** [comment]
@d10r tagging for visibility

**Review by d10r — APPROVED** [review]
Looks good to me.
Tried to test with an example, but can't find an npm package. 
What's needed to get it added to this list? https://github.com/superfluid-finance/protocol-monorepo/pull/950#issuecomment-1176186816

Also, was it a conscious decision to publish it in the global namespace vs under @superfluid-finance? Do we have guidelines for how to make that decision?

**Comment by jtriley2p** [comment]
@d10r Ideally we publish this as `@superfluid-finance/hardhat-deployer`, that was my mistake. I changed the README file to reflect this.

As for the npm package, it is not published yet. The objective was to publish it after it was reviewed and merged into the monorepo.

**Review by hellwolf — APPROVED** [review]
LET'S GO

**Comment by jtriley2p** [comment]
🔥

**Pull request merged**
