### PR TITLE
Use `abi.encodeCall`

### LINKED ISSUE #797: [ETHEREUM-CONRACTS] Use abi.encodeCall
Starting from [solidity v0.8.11](https://forum.soliditylang.org/t/solidity-v0-8-11-is-here-first-implementation-of-language-server-and-abi-encodecall/723), `abi.encodeCall` is available as an type-safe alternative to abi.encodeWithSelector when you have the access to the function pointer.

We should use it as much as possible.

### PR DESCRIPTION
**Pull request by 0xdavinchee**
* abi.encodeWithSelector replaced by abi.encodeCall
* There are a few places where this was not replaced because there was no access to the function pointer or we had to return/take a function pointer for the function

### CODE REVIEW

**Comment by hellwolf** [comment]
> There are a few places where this was not replaced because there was no access to the function pointer or we had to return/take a function pointer for the function

fwiw:

```
$ find packages/ethereum-contracts/ examples/ -type f -name '*.sol' -and -not -path '*/node_modules/*' | xargs grep abi.encodeWithSelector --color
packages/ethereum-contracts/contracts/agreements/AgreementLibrary.sol:                bytes memory callData = abi.encodeWithSelector(
packages/ethereum-contracts/contracts/agreements/AgreementLibrary.sol:                bytes memory callData = abi.encodeWithSelector(
packages/ethereum-contracts/contracts/interfaces/superfluid/ISuperfluid.sol:     * abi.encodeWithSelector. The context parameter should be set to "0x",
packages/ethereum-contracts/contracts/mocks/MultiFlowTesterApp.sol:            bytes memory callData = abi.encodeWithSelector(
examples/simple-acl-close/src/SimpleACLCloseResolver.sol:        execPayload = abi.encodeWithSelector(
```

**Review by hellwolf — APPROVED** [review]
great stuff

maybe SimpleACLCloseResolver.sol too?

**Comment by 0xdavinchee** [comment]
> great stuff
> 
> maybe SimpleACLCloseResolver.sol too?

yeah, will have to add host to the constructor prolly

**Comment by hellwolf** [comment]
> > great stuff
> > maybe SimpleACLCloseResolver.sol too?
> 
> yeah, will have to add host to the constructor prolly

do you, can't you just access it through the contract definition directly?

**Comment by 0xdavinchee** [comment]
> > > great stuff
> > > maybe SimpleACLCloseResolver.sol too?
> > 
> > 
> > yeah, will have to add host to the constructor prolly
> 
> do you, can't you just access it through the contract definition directly?

nope, otherwise you get this error:

```
TypeError: Cannot implicitly convert component at position 1 from "bytes memory" to "bytes calldata".
   --> src/SimpleACLCloseResolver.sol:105:17:
    |
105 |                 callData,
    |                 ^^^^^^^^


TypeError: Cannot implicitly convert component at position 2 from "literal_string "0x"" to "bytes calldata".
   --> src/SimpleACLCloseResolver.sol:106:17:
    |
106 |                 "0x"
    |                 ^^^^
```

**Comment by hellwolf** [comment]
> > > > great stuff
> > > > maybe SimpleACLCloseResolver.sol too?
> > > 
> > > 
> > > yeah, will have to add host to the constructor prolly
> > 
> > 
> > do you, can't you just access it through the contract definition directly?
> 
> nope, otherwise you get this error:
> 
> ```
> TypeError: Cannot implicitly convert component at position 1 from "bytes memory" to "bytes calldata".
>    --> src/SimpleACLCloseResolver.sol:105:17:
>     |
> 105 |                 callData,
>     |                 ^^^^^^^^
> 
> 
> TypeError: Cannot implicitly convert component at position 2 from "literal_string "0x"" to "bytes calldata".
>    --> src/SimpleACLCloseResolver.sol:106:17:
>     |
> 106 |                 "0x"
>     |                 ^^^^
> ```

https://github.com/ethereum/solidity/issues/12448

**Pull request merged**
