### PR TITLE
Re-write rewards-distribution-token using new sdk-core

### PR DESCRIPTION
**Pull request by andresmayorca**
Rewriting the rewards-distribution-token example using the new version of the sdk-core

### CODE REVIEW

**Comment by saflamini** [comment]
> Rewriting the rewards-distribution-token example using the new version of the sdk-core

Hey @ethcode1 - a few final changes are required here:

1) Pull the most recent updates to the monorepo's examples folder into your local branch
2) Remove the 'hardhat' suffix from the filename. Your file should just be the rewards-distribution-token, and there shouldn't be a duplicate version that uses truffle any longer. You can remove this.
3) Please add a build-and-test.sh script to your folder. This script should look like this: https://github.com/superfluid-finance/protocol-monorepo/blob/dev/examples/tradeable-cashflow/tradeable-cashflow-hardhat/build-and-test.sh

**Review by saflamini — APPROVED** [review]
Looks good @ethcode1

**Review by saflamini — APPROVED** [review]

**Review by saflamini — APPROVED** [review]

**Review by saflamini — APPROVED** [review]

**Review by saflamini — APPROVED** [review]

**Comment by hellwolf** [comment]
for some reason, the build didn't trigger: `ci.feature.yml` has some deficiency. I will merge by force this time

**Comment by 0xdavinchee** [comment]
@hellwolf this is due to the trigger:

```
    paths:
      - "packages/**"
      - ".github/workflows/**"
```
it no longer runs for example project changes and this makes sense because we aren't running any checks for the example projects in the `ci.feature.yml` workflow.

**Comment by hellwolf** [comment]
they can be triggered, but the workflow is written such that they will be mostly skipped. and that would allow the status to be considered "checked and passed".

**Pull request merged**
