### PR TITLE
[ETHEREUM-CONTRACTS] BatchLiquidator: don't revert for non-transferrable SuperTokens

### PR DESCRIPTION
**Pull request by d10r**
[ABToken](https://console.superfluid.finance/optimism-mainnet/supertokens/0x167832BAF36D1AC0aF9e8d8aD329Fa418BeD5cD9?tab=streams) turned out to be non-transferrable, which caused liquidation txs using BatchLiquidator to revert.
This PR allows transfers in the batch contract to fail.

TBD: deploy and add new contract addresses to metadata

### CODE REVIEW

**Comment by hellwolf** [comment]
We will deploy this to all networks. But it's not a high priority yet.

**Comment by hellwolf** [comment]
We will merge, but not necessarily deploy to all networks.

**Review by hellwolf — APPROVED** [review]

**Review by hellwolf — CHANGES_REQUESTED** [review]
change of mind.

Must have test case.

**Comment by ngmachado** [comment]
This update introduce BatchLiquidator tests for Custom SuperToken that revert on `transferFrom`

**Comment by philipandersson** [comment]
Ready for review.

**Comment by philipandersson** [comment]
@hellwolf Please review as soon as you've got some time. Or do you want to dedicate one _Let's discuss to this_?

**Comment by philipandersson** [comment]
@hellwolf Please review as soon as you've got some time. Or do you want to dedicate one _Let's discuss to this_?

**Review by 0xdavinchee — APPROVED** [review]
looks good - LGTM

**Review by hellwolf — APPROVED** [review]
looks good.

**Pull request merged**
